import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillInstagram, AiFillMail} from 'react-icons/ai'
import Image from 'next/image'
import Astro from'../pages/Astro.png';
import design from'../pages/design.png';
import robot from '../pages/robot.png';
import consulting from '../pages/consulting.png'
import web1 from '../pages/web1.png'
import web2 from '../pages/web2.png'
import web3 from '../pages/web3.png'
import web4 from'../pages/web4.png'
import web5 from '../pages/web5.png'
import web6 from '../pages/web6.png'
import {useState} from 'react';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return(
    <div className = {darkMode ? 'dark' : ""}>
      <Head>
        <title>Allen Abraham Portfolio</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href='/favicon.ico'/>
      </Head>

      <main className="bg-white px-10 md:px-10 lg:px-40 dark:bg-gray-900">
      <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="font-burtons text-xl dark:text-white">Allen Abraham</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={()=> setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"href='#'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Allen Abraham
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Student
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800  max-w-xl mx-auto md:text-lg dark:text-white">
              I am a student that studies in Stem Innovation Academy and will graduate in 2025. I have interest in business, robotics, and programming (especially web-development). Have a look at my work and experiences!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/RishiSunak"><AiFillTwitterCircle /></a>
              <a href="https://www.instagram.com/aa_spiffy/"><AiFillInstagram  /></a>
              <a href="https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox?compose=new"><AiFillMail /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96 ">
              <Image src={Astro} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section>
          <div >
            <h3 className="text-3xl py-3 dark:text-white">Interests</h3>
            <p className ="text-md py-2 leading-8 text-gray-800 dark:text-white">
              I want to go into software engineering because I enjoy problem-solving and have an interest in technology and its potential to make a positive impact on society. I have done work in
              <span className="text-teal-500"> robotics </span>
              and have been working on <span className="text-teal-500"> web-development </span>
              and have worked with people of all backgrounds to create solutions and design ideas for the voices of the youth.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I offer from a wide range of services such as mechanical work, consulting, and programming.
            </p>
            <div className="lg:flex gap-10">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white">
                <Image src={design} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Creating Beautiful Designs</h3>
                <p className="py-2">
                Creating desings catered towards you and your company following design theory.
                </p>
                <h4 className="py-4 text-teal-600">Tools I Use to Design</h4>
                <p className = "text-gray-800 py-1">React(learning)</p>
                <p className = "text-gray-800 py-1">Ruby on Rails(learning)</p> 
                <p className = "text-gray-800 py-1">HTML, CSS, Javascript</p>
              </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white">
              <Image src={robot} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Working With Robots</h3>
              <p className="py-2">
                Creating a deisnging robots that can be used for certain tasks
              </p>
              <h4 className="py-4 text-teal-600">Skills</h4>
              <p className = "text-gray-800 py-1">Programming in Python and Java(learning)</p>
              <p className = "text-gray-800 py-1">Mechanical</p> 
              <p className = "text-gray-800 py-1">Electrical</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white">
              <Image src={consulting} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">Working with people</h3>
              <p className="py-2">
                Voicing people in our society and empowering the youth.
              </p>
              <h4 className="py-4 text-teal-600">Skills</h4>
              <p className = "text-gray-800 py-1">Public Speaker</p>
              <p className = "text-gray-800 py-1">Confidence</p> 
              <p className = "text-gray-800 py-1">Social</p>
            </div>
          </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">
              Portfolio
            </h3>
            <p className ="text-md py-2 leading-8 text-gray-800 dark:text-white">
              I want to go into software engineering because I enjoy problem-solving and have an interest in technology and its potential to make a positive impact on society. I have done work in
              <span className="text-teal-500"> robotics </span>
              , have worked on <span className="text-teal-500"> web-development </span>
              and have worked with people of all backgrounds to create solutions and design ideas for the voices of the youth.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap rounded-lg object-cover">
            <div className = "basis-1/3 flex-1"><Image src={web1} className = "rounded-lg object-cover" width={"100%"} height={"100"} layout={"responsive"}/></div>
            <div className = "basis-1/3 flex-1"><Image src={web2} className = "rounded-lg object-cover" width={"100%"} height={"100"} layout={"responsive"}/></div>
            <div className = "basis-1/5 flex-1"><Image src={web3} className = "rounded-lg object-cover" width={"100%"} height={"100"} layout={"responsive"}/></div>
            <div className = "basis-1/3 flex-1"><Image src={web4} className = "rounded-lg object-cover" width={"100%"} height={"100"} layout={"responsive"}/></div>
            <div className = "basis-1/3 flex-1"><Image src={web5} className = "rounded-lg object-cover" width={"100%"} height={"100"} layout={"responsive"}/></div>
            <div className = "basis-1/3 flex-1"><Image src={web6} className = "rounded-lg object-cover" width={"100%"} height={"100"} layout={"responsive"}/></div>
          </div>
        </section>
      </main>
    </div>
  )
}